---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

suites:
  - name: lwrp_install
    run_list:
      - recipe[mod_security2::install]
      - recipe[nginx]
    attributes:
      mod_security2:
        platform: nginx

  - name: lwrp_configure
    run_list:
      - recipe[mod_security2::install]
      - recipe[mod_security2::configure]

  - name: nginx_install
    run_list:
      - recipe[mod_security2::install]
      - recipe[mod_security2::configure]
      - recipe[nginx::default]
    attributes:
      mod_security2:
        platform: nginx
      nginx:
        install_method: source
        source:
          modules:
            - mod_security2::nginx_module
