---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

suites:
  - name: lwrp_nginx
    run_list:
      - recipe[mod_security2]
    attributes:
      mod_security2:
        platform: nginx

  - name: nginx_install
    run_list:
      - recipe[mod_security2]
      - recipe[mod_security2::nginx_module]
      - recipe[nginx::source]
    attributes:
      mod_security2:
        platform: nginx
